### ISSUE TITLE
Provision a default moonraker.conf

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/printnanny-os#104]
**Describe your Request**
If you don't provide a `moonraker.conf` file, `moonraker.service` will fail to start with the following error. 

Instead, let's provision a default `moonraker.conf` and flash an info bar informing the user 1) they're running the default conf 2) how to change the conf.
```
Oct 20 10:08:54 octo-0-4-0 python3[784]: Traceback (most recent call last):
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/moonraker.py", line 460, in main
Oct 20 10:08:54 octo-0-4-0 python3[784]:     server = Server(app_args, file_logger, event_loop)
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/moonraker.py", line 67, in __init__
Oct 20 10:08:54 octo-0-4-0 python3[784]:     self.config = config = self._parse_config()
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/moonraker.py", line 129, in _parse_config
Oct 20 10:08:54 octo-0-4-0 python3[784]:     config = confighelper.get_configuration(self, self.app_args)
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/confighelper.py", line 1040, in get_configuration
Oct 20 10:08:54 octo-0-4-0 python3[784]:     source.read_file(start_path)
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/confighelper.py", line 1028, in read_file
Oct 20 10:08:54 octo-0-4-0 python3[784]:     self._parse_file(main_conf, [])
Oct 20 10:08:54 octo-0-4-0 python3[784]:   File "/opt/moonraker/moonraker/confighelper.py", line 1013, in _parse_file
Oct 20 10:08:54 octo-0-4-0 python3[784]:     raise ConfigError(
Oct 20 10:08:54 octo-0-4-0 python3[784]: confighelper.ConfigError: Configuration File Not Found: '/home/printnanny/.config/klipper/moonraker.conf''
Oct 20 10:08:54 octo-0-4-0 python3[784]: [moonraker.py:main()] - Server Shutdown
```

**Comment by leigh-johnson** [comment]
Done - will be released in v0.4.2
