### ISSUE TITLE
Upgrade OctoPrint to version 1.9.0

### ISSUE THREAD

**Issue by leigh-johnson** [bitsy-ai/printnanny-os#295]
**Describe your Request**
https://octoprint.org/blog/2023/03/22/new-release-candidate-1.9.0rc3

**Comment by leigh-johnson** [comment]
Python 3.11.2
OctoPrint 1.9.1

```
Jul 15 12:59:14 rpi4-073 octoprint[715]: Traceback (most recent call last):
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "<frozen runpy>", line 198, in _run_module_as_main
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "<frozen runpy>", line 88, in _run_code
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/__main__.py", line 6, in <module>
Jul 15 12:59:14 rpi4-073 octoprint[715]:     octoprint.main()
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/__init__.py", line 1008, in main
Jul 15 12:59:14 rpi4-073 octoprint[715]:     octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
Jul 15 12:59:14 rpi4-073 octoprint[715]:     return self.main(*args, **kwargs)
Jul 15 12:59:14 rpi4-073 octoprint[715]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1055, in main
Jul 15 12:59:14 rpi4-073 octoprint[715]:     rv = self.invoke(ctx)
Jul 15 12:59:14 rpi4-073 octoprint[715]:          ^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1657, in invoke
Jul 15 12:59:14 rpi4-073 octoprint[715]:     return _process_result(sub_ctx.command.invoke(sub_ctx))
Jul 15 12:59:14 rpi4-073 octoprint[715]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
Jul 15 12:59:14 rpi4-073 octoprint[715]:     return ctx.invoke(self.callback, **ctx.params)
Jul 15 12:59:14 rpi4-073 octoprint[715]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/core.py", line 760, in invoke
Jul 15 12:59:14 rpi4-073 octoprint[715]:     return __callback(*args, **kwargs)
Jul 15 12:59:14 rpi4-073 octoprint[715]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
Jul 15 12:59:14 rpi4-073 octoprint[715]:     return f(get_current_context(), *args, **kwargs)
Jul 15 12:59:14 rpi4-073 octoprint[715]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/cli/server.py", line 317, in serve_command
Jul 15 12:59:14 rpi4-073 octoprint[715]:     run_server(
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/cli/server.py", line 163, in run_server
Jul 15 12:59:14 rpi4-073 octoprint[715]:     octoprint_server.run()
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/server/__init__.py", line 389, in run
Jul 15 12:59:14 rpi4-073 octoprint[715]:     self._setup_i18n(app, additional_folders=additional_translation_folders)
Jul 15 12:59:14 rpi4-073 octoprint[715]:   File "/usr/lib/python3.11/site-packages/octoprint/server/__init__.py", line 1590, in _setup_i18n
Jul 15 12:59:14 rpi4-073 octoprint[715]:     babel = Babel(app, locale_selector=self._get_locale)
Jul 15 12:59:14 rpi4-073 octoprint[715]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 15 12:59:14 rpi4-073 octoprint[715]: TypeError: Babel.__init__() got an unexpected keyword argument 'locale_selector'
```


```
-----------------------
Build Info:  |
-----------------------
IMAGE_NAME = printnanny-release-image-raspberrypi4-64-20230714014336
DISTRO_PRETTY = PrintNanny Linux 0.7.3 (Garnet)
VARIANT_NAME = PrintNanny OS Core
VARIANT_ID = core
DISTRO = printnanny
DISTRO_NAME = PrintNanny Linux
DISTRO_VERSION = 0.7.3
DISTRO_CODENAME = Garnet
ID_LIKE = BitsyLinux
HOME_URL = https://printnanny.ai
BUG_REPORT_URL = https://github.com/bitsy-ai/printnanny-os/issues
YOCTO_VERSION = 4.1.2
YOCTO_CODENAME = Langdale
MACHINE = raspberrypi4-64
TUNE_PKGARCH = cortexa72
-----------------------
Layer Revisions:      |
-----------------------
meta              = mickledore:ddb298ce894482467d82699d223c5555baad6591
meta-poky         = mickledore:ddb298ce894482467d82699d223c5555baad6591
meta-yocto-bsp    = mickledore:ddb298ce894482467d82699d223c5555baad6591
meta-oe           = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
meta-networking   = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
meta-python       = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
meta-webserver    = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
meta-initramfs    = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
meta-bitsy        = octoprint-1.9.1:dc7658d4b8e017f086d580c1f5075be4e7c5b335
meta-microcontroller = mickledore:a848733698649628d0c3e34ae04ced0ee6ce3aee
meta-neural-network = mickledore:39f06bfa582eedc8621df677bb5cf044e9481309
meta-raspberrypi  = issue-1167-raspberrypi-hq-camera:26a25492a639310bb94afd4b2b066895c9217bad
meta-swupdate     = master:19007b03a1d96eca38e12f3bbd7bb296aea50bab
meta-printnanny   = octoprint-1.9.1:dc7658d4b8e017f086d580c1f5075be4e7c5b335
meta-multimedia   = mickledore-polkit-src:4321a5fd17fa2c307ca579ae76b921fb4c560bfa
```
